# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo01' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Masonry','1.0.0'

  # Pods for Demo01

  target 'Demo01Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Demo01UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
